FROM node:alpine

# USER roshadaafzal

WORKDIR '/app' 
# Above command sets ownership to root

COPY package.json .
RUN npm install
COPY . . 

# COPY --chown=node:node ./package.json ./
# RUN npm install
# COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]